SgUntypedAttribute* rose_build_SgUntypedAttribute(int arg1, char* arg2);
SgUntypedInitializedName* rose_build_SgUntypedInitializedName(SgUntypedType* arg1, char* arg2);
SgUntypedFile* rose_build_SgUntypedFile(SgUntypedGlobalScope* arg1);
SgUntypedStatementList* rose_build_SgUntypedStatementList();
SgUntypedFunctionDeclarationList* rose_build_SgUntypedFunctionDeclarationList();
SgUntypedInitializedNameList* rose_build_SgUntypedInitializedNameList();
SgUntypedValueExpression* rose_build_SgUntypedValueExpression(int arg1, char* arg2, SgUntypedType* arg3);
SgUntypedArrayReferenceExpression* rose_build_SgUntypedArrayReferenceExpression(int arg1);
SgUntypedOtherExpression* rose_build_SgUntypedOtherExpression(int arg1);
SgUntypedFunctionCallOrArrayReferenceExpression* rose_build_SgUntypedFunctionCallOrArrayReferenceExpression(int arg1);
SgUntypedReferenceExpression* rose_build_SgUntypedReferenceExpression(int arg1, char* arg2);
SgUntypedAssignmentStatement* rose_build_SgUntypedAssignmentStatement(char* arg1, int arg2, SgUntypedExpression* arg3, SgUntypedExpression* arg4);
SgUntypedFunctionCallStatement* rose_build_SgUntypedFunctionCallStatement(char* arg1, int arg2);
SgUntypedNamedStatement* rose_build_SgUntypedNamedStatement(char* arg1, int arg2, char* arg3);
SgUntypedOtherStatement* rose_build_SgUntypedOtherStatement(char* arg1, int arg2);
SgUntypedImplicitDeclaration* rose_build_SgUntypedImplicitDeclaration(char* arg1, int arg2);
SgUntypedVariableDeclaration* rose_build_SgUntypedVariableDeclaration(char* arg1, int arg2, SgUntypedType* arg3, SgUntypedInitializedNameList* arg4);
SgUntypedModuleDeclaration* rose_build_SgUntypedModuleDeclaration(char* arg1, int arg2, char* arg3, SgUntypedModuleScope* arg4, SgUntypedNamedStatement* arg5);
SgUntypedProgramHeaderDeclaration* rose_build_SgUntypedProgramHeaderDeclaration(char* arg1, int arg2, char* arg3, SgUntypedInitializedNameList* arg4, SgUntypedType* arg5, SgUntypedFunctionScope* arg6, SgUntypedNamedStatement* arg7);
SgUntypedSubroutineDeclaration* rose_build_SgUntypedSubroutineDeclaration(char* arg1, int arg2, char* arg3, SgUntypedInitializedNameList* arg4, SgUntypedType* arg5, SgUntypedFunctionScope* arg6, SgUntypedNamedStatement* arg7);
SgUntypedFunctionScope* rose_build_SgUntypedFunctionScope(char* arg1, int arg2, SgUntypedDeclarationStatementList* arg3, SgUntypedStatementList* arg4, SgUntypedFunctionDeclarationList* arg5);
SgUntypedModuleScope* rose_build_SgUntypedModuleScope(char* arg1, int arg2, SgUntypedDeclarationStatementList* arg3, SgUntypedStatementList* arg4, SgUntypedFunctionDeclarationList* arg5);
SgUntypedGlobalScope* rose_build_SgUntypedGlobalScope(char* arg1, int arg2, SgUntypedDeclarationStatementList* arg3, SgUntypedStatementList* arg4, SgUntypedFunctionDeclarationList* arg5);
SgUntypedArrayType* rose_build_SgUntypedArrayType(char* arg1, SgUntypedExpression* arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, SgUntypedExpression* arg9, char* arg10, int arg11);
SgUntypedDeclarationStatementList* rose_build_SgUntypedDeclarationStatementList();
SgUntypedScope* rose_build_SgUntypedScope(char* arg1, int arg2, SgUntypedDeclarationStatementList* arg3, SgUntypedStatementList* arg4, SgUntypedFunctionDeclarationList* arg5);
SgUntypedBlockStatement* rose_build_SgUntypedBlockStatement(char* arg1, int arg2, char* arg3, SgUntypedScope* arg4, SgUntypedNamedStatement* arg5);
SgUntypedUnaryOperator* rose_build_SgUntypedUnaryOperator(int arg1, int arg2, char* arg3, SgUntypedExpression* arg4);
SgUntypedBinaryOperator* rose_build_SgUntypedBinaryOperator(int arg1, int arg2, char* arg3, SgUntypedExpression* arg4, SgUntypedExpression* arg5);
SgUntypedType* rose_build_SgUntypedType(char* arg1);
