INTERFACE OPERATOR(.unaryop.)
END INTERFACE OPERATOR(.unaryop.)
INTERFACE OPERATOR(.binaryop.)
END INTERFACE OPERATOR(.binaryop.)
INTERFACE OPERATOR(**)
END INTERFACE OPERATOR(**)
INTERFACE OPERATOR(//)
END INTERFACE OPERATOR(//)
END PROGRAM
