INTEGER, PARAMETER :: foo = 8
INTEGER(KIND=4), PARAMETER :: i = 4
INTEGER(KIND=4) :: p
INTEGER(KIND=foo) :: bar
INTEGER(KIND=8) :: j
INTEGER(KIND=KIND(4)) :: k
INTEGER(KIND=i) :: m
INTEGER(KIND=KIND(j)) :: n
INTEGER(KIND=i) :: o
INTEGER(KIND=SELECTED_INT_KIND(12)) :: d
REAL(KIND=4) :: q
END PROGRAM
