SUBROUTINE whoot(str_star)
INTEGER, PARAMETER :: a = 13
CHARACTER(1) :: str1
CHARACTER(2) :: str2
CHARACTER(3) :: str3
CHARACTER(a) :: stra
CHARACTER(*) :: str_star
CHARACTER(:), ALLOCATABLE :: str_colon
END SUBROUTINE

