MODULE boohoo
TYPE woohoo
  INTEGER, POINTER, DIMENSION(:) :: ugly
  INTEGER, ALLOCATABLE, CODIMENSION[:] :: bar
  REAL, POINTER :: lies1
  REAL, ALLOCATABLE :: lies2(:,:)
  REAL, POINTER, PRIVATE :: foo
  INTEGER, ALLOCATABLE :: this(:)
  INTEGER, ALLOCATABLE, PRIVATE :: that
END TYPE
END MODULE
