MODULE points
TYPE POINT
  REAL :: X, Y
CONTAINS
PROCEDURE, PASS :: LENGTH => POINT_LENGTH
END TYPE POINT
TYPE, EXTENDS(POINT) :: POINT_3D
  REAL :: Z
CONTAINS
PROCEDURE, PASS :: LENGTH => POINT_3D_LENGTH
END TYPE POINT_3D

CONTAINS

REAL FUNCTION POINT_LENGTH(A,B)
CLASS(POINT), INTENT(IN) :: A, B
POINT_LENGTH = SQRT((A%X-B%X)**2+(A%Y-B%Y)**2)
END FUNCTION POINT_LENGTH
REAL FUNCTION POINT_3D_LENGTH(A,B)
CLASS(POINT_3D), INTENT(IN) :: A
CLASS(POINT), INTENT(IN) :: B
SELECT TYPE (B)
  CLASS IS (POINT_3D)
END SELECT
END FUNCTION point_3d_length
END MODULE points
