MODULE attr_spec
INTEGER, PRIVATE :: a
INTEGER, ALLOCATABLE :: b
INTEGER, ASYNCHRONOUS :: c
INTEGER, CODIMENSION[*] :: co
INTEGER, DIMENSION(7) :: d
INTEGER, EXTERNAL :: e
INTEGER, BIND(C) :: h
INTEGER, PARAMETER :: j = 13
INTEGER, POINTER :: k
INTEGER, PROTECTED :: l
INTEGER, SAVE :: m
INTEGER, TARGET :: n
INTEGER, VOLATILE :: p

CONTAINS

SUBROUTINE foofoo(f,i,o)
INTEGER, INTENT(IN) :: f
INTEGER, OPTIONAL :: i
INTEGER, CONTIGUOUS, DIMENSION(:), POINTER :: cont
INTEGER, INTRINSIC :: sqrt
INTEGER, VALUE :: o
END SUBROUTINE foofoo

END MODULE attr_spec
